### ISSUE TITLE
Django version compatibility

### ISSUE THREAD

**Issue by AntonOfTheWoods** [patriciaborges/django-model-cache#1]
I have had a bit of a play with the code trying to get it to work but on 2.1 I am getting the following error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/bla/.virtualenvs/virty/lib/python3.6/site-packages/django/db/models/manager.py", line 192, in __get__
    return cls._meta.managers_map[self.manager.name]
```
Even though CacheController doesn't inherit from models.Manager it appears to be treated as a manager. I tried making CacheController inherit and various variations on that but I keep getting the same error.
Could this be a Django 2.1+ thing

**Comment by AntonOfTheWoods** [comment]
Sorry, missed the tox file. Would be great to have >= 1.10 support!
